### ISSUE TITLE
Crash at @pause

### ISSUE THREAD

**Issue by eboston** [dattas/OctoPrint-Atcommands#1]
Was trying out your plugin and when it got to the @pause I put in, the following occurred:

2015-02-08 12:18:18,497 - octoprint.util.comm - ERROR - Something crashed inside the serial connection loop, please report this in OctoPrint's bug tracker:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.2.0_dev_477_g5c75676-py2.7.egg/octoprint/util/comm.py", line 961, in _monitor
    self._sendNext()
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.2.0_dev_477_g5c75676-py2.7.egg/octoprint/util/comm.py", line 1089, in _sendNext
    self._sendCommand(line, True)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.2.0_dev_477_g5c75676-py2.7.egg/octoprint/util/comm.py", line 1136, in _sendCommand
    hook_cmd = self._gcode_hooks[hook](self, cmd)
  File "/usr/local/lib/python2.7/dist-packages/octoprint_atcommands/__init__.py", line 69, in hook_atcommand
    return methods[atcommandHandler](comm_obj, cmd)
  File "/usr/local/lib/python2.7/dist-packages/octoprint_atcommands/**init**.py", line 78, in atcommand_pause
    for line in s.get(["at_pause_commands"]).splitlines():
AttributeError: 'NoneType' object has no attribute 'splitlines'

Earlier in the log, I spotted these entries:

2015-02-08 09:20:45,072 - octoprint.plugins.atcommands - INFO - Got at pause commands to be: None
2015-02-08 09:20:45,632 - octoprint.plugins.atcommands - INFO - Got at pause commands to be: None

Using Version: 1.2.0-dev-488-g6cdd8de (devel branch) of OctoPrint

**Comment by eboston** [comment]
Is this plugin still being supported?

**Comment by dattas** [comment]
@eboston currently this plugin only semi works, this is due to how Octoprint currently handles pausing. The octoprint branch commRefactoring-commandtracking is the only branch that is close to handling pausing what I feel is correctly (aka what repetier-host, pronterface, cura, and others do on pause). Recently the plugin system changed so I need to update this project, I will attempt to update it to the newest standards, but until the pausing functionality works properly, this plugin will likely remain in limbo due to pausing within octoprint causing print failures.
